<!doctype html>
<html lang="en">
    @template.head()

    <body>
        @template.header()
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias amet debitis, doloremque est harum iusto minus numquam quos. Exercitationem inventore minima nemo ut vitae. Asperiores commodi facere pariatur recusandae tenetur.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias amet debitis, doloremque est harum iusto minus numquam quos. Exercitationem inventore minima nemo ut vitae. Asperiores commodi facere pariatur recusandae tenetur.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias amet debitis, doloremque est harum iusto minus numquam quos. Exercitationem inventore minima nemo ut vitae. Asperiores commodi facere pariatur recusandae tenetur.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias amet debitis, doloremque est harum iusto minus numquam quos. Exercitationem inventore minima nemo ut vitae. Asperiores commodi facere pariatur recusandae tenetur.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias amet debitis, doloremque est harum iusto minus numquam quos. Exercitationem inventore minima nemo ut vitae. Asperiores commodi facere pariatur recusandae tenetur.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias amet debitis, doloremque est harum iusto minus numquam quos. Exercitationem inventore minima nemo ut vitae. Asperiores commodi facere pariatur recusandae tenetur.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias amet debitis, doloremque est harum iusto minus numquam quos. Exercitationem inventore minima nemo ut vitae. Asperiores commodi facere pariatur recusandae tenetur.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias amet debitis, doloremque est harum iusto minus numquam quos. Exercitationem inventore minima nemo ut vitae. Asperiores commodi facere pariatur recusandae tenetur.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias amet debitis, doloremque est harum iusto minus numquam quos. Exercitationem inventore minima nemo ut vitae. Asperiores commodi facere pariatur recusandae tenetur.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias amet debitis, doloremque est harum iusto minus numquam quos. Exercitationem inventore minima nemo ut vitae. Asperiores commodi facere pariatur recusandae tenetur.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias amet debitis, doloremque est harum iusto minus numquam quos. Exercitationem inventore minima nemo ut vitae. Asperiores commodi facere pariatur recusandae tenetur.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias amet debitis, doloremque est harum iusto minus numquam quos. Exercitationem inventore minima nemo ut vitae. Asperiores commodi facere pariatur recusandae tenetur.</p>
        @template.footer()
    </body>

</html>