CREATE TABLE "user" (
	id INTEGER GENERATED ALWAYS AS IDENTITY,
	email VARCHAR(100) NOT NULL,
	password VARCHAR(255) NOT NULL,
	username VARCHAR(100) NOT NULL,
	created_at TIMESTAMPTZ NOT NULL,
	UNIQUE (email),
	UNIQUE (username)
);


---

CREATE TABLE country (
	id INTEGER GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(100) NOT NULL,
	iso2 VARCHAR(2) NOT NULL,
	PRIMARY KEY (id),
	UNIQUE (name),
	UNIQUE (iso2)
);

CREATE TABLE currency (
	id INTEGER GENERATED ALWAYS AS IDENTITY,
	country_id INTEGER NOT NULL,
	name VARCHAR(50) NOT NULL,
	code VARCHAR(10) NOT NULL,
	PRIMARY KEY (id),
	UNIQUE (country_id),
	FOREIGN KEY(country_id) REFERENCES country (id) ON DELETE CASCADE
);

CREATE TABLE company (
	id INTEGER GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(50) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE exchange (
	id INTEGER GENERATED ALWAYS AS IDENTITY,
	code VARCHAR(10) NOT NULL,
	name VARCHAR(50) NOT NULL,
	country_id INTEGER NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(country_id) REFERENCES country (id) ON DELETE CASCADE
);

CREATE TABLE ticker (
	id INTEGER GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(100) NOT NULL,
	company_id INTEGER NOT NULL,
	exchange_id INTEGER NOT NULL,
	symbol VARCHAR(40) NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(company_id) REFERENCES company (id) ON DELETE CASCADE,
	FOREIGN KEY(exchange_id) REFERENCES exchange (id) ON DELETE CASCADE
);